<?php
/**
 * $Id: xoops_version.php v 1.00 21 June 2005 John N Exp $
 * Module: WF-Links
 * Version: v1.0.3
 * Release Date: 21 June 2005
 * Developer: John N
 * Team: WF-Projects
 * Licence: GNU
 */
$modversion['name'] = _MI_WFB_NAME;
$modversion['version'] = "1.15";
$modversion['releasedate'] = "03 March 2008";
$modversion['status'] = "RC-2";
$modversion['description'] = _MI_WFB_DESC;
$modversion['license'] = "GPL see LICENSE";
$modversion['image'] = "images/wfb_slogo.gif";
$modversion['iconsmall'] = "images/wfbooks_iconsmall.png";
$modversion['iconbig'] = "images/wfbooks_iconbig.png";
$modversion['dirname'] = "wfbooks";

$modversion['author'] = "Version developers: John N (Lead Developer)";
$modversion['credits'] = "WF-Projects Team: Based on WF-Downloads, thanks to the dream-team for some code snippits.";
$modversion['teammembers'] = "amayer, bender, david, dqflyer, draven, frankblack, gladiac, hervet, jackj, mercibe, John N, phppp, predator, reliableSol, tom, xpider, xtheme, mcdonald (version 1.03B and higher)";
$modversion['author_realname'] = "WF-Project Team";
$modversion['author_website_url'] = "http://wf-projects.com";
$modversion['author_website_name'] = "WF-Projects";
$modversion['author_email'] = "webmaster@wf-projects.com";
$modversion['demo_site_url'] = "http://wf-projects.com/modules/wfbooks/";
$modversion['demo_site_name'] = "WF-Projects";
$modversion['support_site_url'] = "http://members.lycos.nl/mcdonaldsstore/phpBB2/index.php?c=4";
$modversion['support_site_name'] = "McDonalds Store Support Forum";
$modversion['submit_bug'] = "http://members.lycos.nl/mcdonaldsstore/phpBB2/viewforum.php?f=8";

$modversion['warning'] = _MI_WFB_WARNINGTEXT;
$modversion['author_credits'] = _MI_WFB_AUTHOR_CREDITSTEXT;
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)

// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/wfbooks.sql";

// Tables created by sql file (without prefix!)
include_once 'include/config.php';
$modversion['tables'][0] = 'wfbooks_broken';
$modversion['tables'][1] = 'wfbooks_cat';
$modversion['tables'][2] = 'wfbooks_links';
$modversion['tables'][3] = 'wfbooks_mod';
$modversion['tables'][4] = 'wfbooks_votedata';
$modversion['tables'][5] = 'wfbooks_indexpage';
$modversion['tables'][6] = 'wfbooks_altcat';

// Launch additional install script to check
// the existence of tables 'wf_resources_types' and 'wf_resources'
$modversion['onInstall'] = '';
//$modversion['onUpdate'] = '';
$modversion['onUpdate'] = 'include/update.php';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "wfbooks_top.php";
$modversion['blocks'][1]['name'] = _MI_WFB_BNAME1;
$modversion['blocks'][1]['description'] = "Shows recently added links";
$modversion['blocks'][1]['show_func'] = "b_wfbooks_top_show";
$modversion['blocks'][1]['edit_func'] = "b_wfbooks_top_edit";
$modversion['blocks'][1]['options'] = "date|10|19";
$modversion['blocks'][1]['template'] = 'wfbooks_block_new.html';
$modversion['blocks'][1]['can_clone'] = true ;

$modversion['blocks'][2]['file'] = "wfbooks_top.php";
$modversion['blocks'][2]['name'] = _MI_WFB_BNAME2;
$modversion['blocks'][2]['description'] = "Shows top clicked links";
$modversion['blocks'][2]['show_func'] = "b_wfbooks_top_show";
$modversion['blocks'][2]['edit_func'] = "b_wfbooks_top_edit";
$modversion['blocks'][2]['options'] = "hits|10|19";
$modversion['blocks'][2]['template'] = 'wfbooks_block_top.html';
$modversion['blocks'][2]['can_clone'] = true ;
// Menu
$modversion['hasMain'] = 1;

/**
 * This part inserts the selected topics as sub items in the Xoops main menu
 */
$module_handler = &xoops_gethandler( 'module' );
$module = &$module_handler -> getByDirname( $modversion['dirname'] );
$cansubmit = 0;
if ( is_object( $module ) )
{
    global $xoopsUser;
    $groups = ( is_object( $xoopsUser ) ) ? $xoopsUser -> getGroups() : XOOPS_GROUP_ANONYMOUS;
    $gperm_handler = &xoops_gethandler( 'groupperm' );
    if ( $gperm_handler -> checkRight( "WFBookSubPerm", 0, $groups, $module -> getVar( 'mid' ) ) )
    {
        $cansubmit = 1;
    } 
} 
if ( $cansubmit == 1 )
{
    $modversion['sub'][0]['name'] = _MI_WFB_SMNAME1;
    $modversion['sub'][0]['url'] = "submit.php";
} 
unset( $cansubmit );

$i = 1;
$modversion['sub'][$i]['name'] = _MI_WFB_SMNAME2;
$modversion['sub'][$i]['url'] = "topten.php?list=hit";

$i++;
$modversion['sub'][$i]['name'] = _MI_WFB_SMNAME3;
$modversion['sub'][$i]['url'] = "topten.php?list=rate";

$i++;
$modversion['sub'][$i]['name'] = _MI_WFB_SMNAME4;
$modversion['sub'][$i]['url'] = "newlist.php?newlinkshowdays=7";
unset( $i );

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "wfbooks_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'lid';
$modversion['comments']['pageName'] = 'singlelink.php';
$modversion['comments']['extraParams'] = array( 'cid' );

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wfbooks_com_approve';
$modversion['comments']['callback']['update'] = 'wfbooks_com_update';

// Templates
$modversion['templates'][1]['file'] = 'wfbooks_brokenlink.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'wfbooks_linkload.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'wfbooks_index.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][5]['file'] = 'wfbooks_ratelink.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'wfbooks_singlelink.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][8]['file'] = 'wfbooks_topten.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'wfbooks_viewcat.html';
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = 'wfbooks_newlistindex.html';
$modversion['templates'][10]['description'] = '';

// Module config setting
$modversion['config'][1]['name'] = 'popular';
$modversion['config'][1]['title'] = '_MI_WFB_POPULAR';
$modversion['config'][1]['description'] = '_MI_WFB_POPULARDSC';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 100;
$modversion['config'][1]['options'] = array( '5' => 5, '10' => 10, '50' => 50, '100' => 100, '200' => 200, '500' => 500, '1000' => 1000 );

$modversion['config'][2]['name'] = 'displayicons';
$modversion['config'][2]['title'] = '_MI_WFB_ICONDISPLAY';
$modversion['config'][2]['description'] = '_MI_WFB_DISPLAYICONDSC';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 1;
$modversion['config'][2]['options'] = array( '_MI_WFB_DISPLAYICON1' => 1, '_MI_WFB_DISPLAYICON2' => 2, '_MI_WFB_DISPLAYICON3' => 3 );

$modversion['config'][41]['name'] = 'daysnew';
$modversion['config'][41]['title'] = '_MI_WFB_DAYSNEW';
$modversion['config'][41]['description'] = '_MI_WFB_DAYSNEWDSC';
$modversion['config'][41]['formtype'] = 'textbox';
$modversion['config'][41]['valuetype'] = 'int';
$modversion['config'][41]['default'] = 10;

$modversion['config'][42]['name'] = 'daysupdated';
$modversion['config'][42]['title'] = '_MI_WFB_DAYSUPDATED';
$modversion['config'][42]['description'] = '_MI_WFB_DAYSUPDATEDDSC';
$modversion['config'][42]['formtype'] = 'textbox';
$modversion['config'][42]['valuetype'] = 'int';
$modversion['config'][42]['default'] = 10;

$modversion['config'][3]['name'] = 'perpage';
$modversion['config'][3]['title'] = '_MI_WFB_PERPAGE';
$modversion['config'][3]['description'] = '_MI_WFB_PERPAGEDSC';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 10;
$modversion['config'][3]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$modversion['config'][35]['name'] = 'admin_perpage';
$modversion['config'][35]['title'] = '_MI_WFB_ADMINPAGE';
$modversion['config'][35]['description'] = '_MI_WFB_AMDMINPAGEDSC';
$modversion['config'][35]['formtype'] = 'select';
$modversion['config'][35]['valuetype'] = 'int';
$modversion['config'][35]['default'] = 10;
$modversion['config'][35]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50, '75' => 75, '100' => 100 );

$qa = ' (A)';
$qd = ' (D)';
$modversion['config'][39]['name'] = 'linkxorder';
$modversion['config'][39]['title'] = '_MI_WFB_ARTICLESSORT';
$modversion['config'][39]['description'] = '_MI_WFB_ARTICLESSORTDSC';
$modversion['config'][39]['formtype'] = 'select';
$modversion['config'][39]['valuetype'] = 'text';
$modversion['config'][39]['default'] = 'title ASC';
$modversion['config'][39]['options'] = array( _MI_WFB_TITLE . $qa => 'title ASC',
                                              _MI_WFB_TITLE . $qd => 'title DESC',
                                              _MI_WFB_SUBMITTED2 . $qa => 'published ASC' ,
                                              _MI_WFB_SUBMITTED2 . $qd => 'published DESC',
                                              _MI_WFB_RATING . $qa => 'rating ASC',
                                              _MI_WFB_RATING . $qd => 'rating DESC',
                                              _MI_WFB_POPULARITY . $qa => 'hits ASC',
                                              _MI_WFB_POPULARITY . $qd => 'hits DESC',
                                              _MI_WFB_COUNTRY . $qa => 'country ASC',
                                              _MI_WFB_COUNTRY . $qd => 'country DESC'
                                             );

$modversion['config'][4]['name'] = 'sortcats';
$modversion['config'][4]['title'] = '_MI_WFB_SORTCATS';
$modversion['config'][4]['description'] = '_MI_WFB_SORTCATSDSC';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'text';
$modversion['config'][4]['default'] = 'weight';
$modversion['config'][4]['options'] = array( 'Weight' => 'weight', 'Title' => 'title');

$modversion['config'][32]['name'] = 'subcats';
$modversion['config'][32]['title'] = '_MI_WFB_SUBCATS';
$modversion['config'][32]['description'] = '_MI_WFB_SUBCATSDSC';
$modversion['config'][32]['formtype'] = 'yesno';
$modversion['config'][32]['valuetype'] = 'int';
$modversion['config'][32]['default'] = 0;

$modversion['config'][34]['name'] = 'form_options';
$modversion['config'][34]['title'] = '_MI_WFB_EDITOR';
$modversion['config'][34]['description'] = '_MI_WFB_EDITORCHOICE';
$modversion['config'][34]['formtype'] = 'select';
$modversion['config'][34]['valuetype'] = 'text';
$modversion['config'][34]['default'] = 'dhtml';
$modversion['config'][34]['options'] =  array(  _MI_WFB_FORM_DHTML => 'dhtml',
                                                _MI_WFB_FORM_DHTMLEXT => 'dhtmlext',
						_MI_WFB_FORM_COMPACT => 'textarea',
						_MI_WFB_FORM_HTMLAREA => 'htmlarea',
						_MI_WFB_FORM_KOIVI => 'koivi',
						_MI_WFB_FORM_FCK => 'fck',
						_MI_WFB_FORM_TINYEDITOR => 'tinyeditor',
						_MI_WFB_FORM_TINYMCE => 'tinymce'
                                              );

$modversion['config'][50]['name'] = 'form_optionsuser';
$modversion['config'][50]['title'] = '_MI_WFB_EDITORUSER';
$modversion['config'][50]['description'] = '_MI_WFB_EDITORCHOICEUSER';
$modversion['config'][50]['formtype'] = 'select';
$modversion['config'][50]['valuetype'] = 'text';
$modversion['config'][50]['default'] = 'dhtml';
$modversion['config'][50]['options'] =  array(  _MI_WFB_FORM_DHTML => 'dhtml',
                                                _MI_WFB_FORM_DHTMLEXT => 'dhtmlext',
						_MI_WFB_FORM_COMPACT => 'textarea',
						_MI_WFB_FORM_HTMLAREA => 'htmlarea',
						_MI_WFB_FORM_KOIVI => 'koivi',
						_MI_WFB_FORM_FCK => 'fck',
						_MI_WFB_FORM_TINYEDITOR => 'tinyeditor',
						_MI_WFB_FORM_TINYMCE => 'tinymce'
                                              );

$modversion['config'][6]['name'] = 'screenshot';
$modversion['config'][6]['title'] = '_MI_WFB_USESHOTS';
$modversion['config'][6]['description'] = '_MI_WFB_USESHOTSDSC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 0;

$modversion['config'][21]['name'] = 'usethumbs';
$modversion['config'][21]['title'] = '_MI_WFB_USETHUMBS';
$modversion['config'][21]['description'] = '_MI_WFB_USETHUMBSDSC';
$modversion['config'][21]['formtype'] = 'yesno';
$modversion['config'][21]['valuetype'] = 'int';
$modversion['config'][21]['default'] = 0;

$modversion['config'][36]['name'] = 'updatethumbs';
$modversion['config'][36]['title'] = '_MI_WFB_IMGUPDATE';
$modversion['config'][36]['description'] = '_MI_WFB_IMGUPDATEDSC';
$modversion['config'][36]['formtype'] = 'yesno';
$modversion['config'][36]['valuetype'] = 'int';
$modversion['config'][36]['default'] = 1;

$modversion['config'][37]['name'] = 'imagequality';
$modversion['config'][37]['title'] = '_MI_WFB_QUALITY';
$modversion['config'][37]['description'] = '_MI_WFB_QUALITYDSC';
$modversion['config'][37]['formtype'] = 'textbox';
$modversion['config'][37]['valuetype'] = 'int';
$modversion['config'][37]['default'] = 100;

$modversion['config'][38]['name'] = 'keepaspect';
$modversion['config'][38]['title'] = '_MI_WFB_KEEPASPECT';
$modversion['config'][38]['description'] = '_MI_WFB_KEEPASPECTDSC';
$modversion['config'][38]['formtype'] = 'yesno';
$modversion['config'][38]['valuetype'] = 'int';
$modversion['config'][38]['default'] = 0;

$modversion['config'][7]['name'] = 'shotwidth';
$modversion['config'][7]['title'] = '_MI_WFB_SHOTWIDTH';
$modversion['config'][7]['description'] = '_MI_WFB_SHOTWIDTHDSC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 140;

$modversion['config'][20]['name'] = 'shotheight';
$modversion['config'][20]['title'] = '_MI_WFB_SHOTHEIGHT';
$modversion['config'][20]['description'] = '_MI_WFB_SHOTHEIGHTDSC';
$modversion['config'][20]['formtype'] = 'textbox';
$modversion['config'][20]['valuetype'] = 'int';
$modversion['config'][20]['default'] = 79;

$modversion['config'][10]['name'] = 'maxfilesize';
$modversion['config'][10]['title'] = '_MI_WFB_MAXFILESIZE';
$modversion['config'][10]['description'] = '_MI_WFB_MAXFILESIZEDSC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 200000;

$modversion['config'][11]['name'] = 'maximgwidth';
$modversion['config'][11]['title'] = '_MI_WFB_IMGWIDTH';
$modversion['config'][11]['description'] = '_MI_WFB_IMGWIDTHDSC';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = 600;

$modversion['config'][12]['name'] = 'maximgheight';
$modversion['config'][12]['title'] = '_MI_WFB_IMGHEIGHT';
$modversion['config'][12]['description'] = '_MI_WFB_IMGHEIGHTDSC';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 600;

$modversion['config'][19]['name'] = 'mainimagedir';
$modversion['config'][19]['title'] = '_MI_WFB_MAINIMGDIR';
$modversion['config'][19]['description'] = '_MI_WFB_MAINIMGDIRDSC';
$modversion['config'][19]['formtype'] = 'textbox';
$modversion['config'][19]['valuetype'] = 'text';
$modversion['config'][19]['default'] = 'modules/wfbooks/images';

$modversion['config'][17]['name'] = 'screenshots';
$modversion['config'][17]['title'] = '_MI_WFB_SCREENSHOTS';
$modversion['config'][17]['description'] = '_MI_WFB_SCREENSHOTSDSC';
$modversion['config'][17]['formtype'] = 'textbox';
$modversion['config'][17]['valuetype'] = 'text';
$modversion['config'][17]['default'] = 'uploads/images/screenshots';

$modversion['config'][18]['name'] = 'catimage';
$modversion['config'][18]['title'] = '_MI_WFB_CATEGORYIMG';
$modversion['config'][18]['description'] = '_MI_WFB_CATEGORYIMGDSC';
$modversion['config'][18]['formtype'] = 'textbox';
$modversion['config'][18]['valuetype'] = 'text';
$modversion['config'][18]['default'] = 'uploads/images/category';

$modversion['config'][23]['name'] = 'dateformat';
$modversion['config'][23]['title'] = '_MI_WFB_DATEFORMAT';
$modversion['config'][23]['description'] = '_MI_WFB_DATEFORMATDSC';
$modversion['config'][23]['formtype'] = 'textbox';
$modversion['config'][23]['valuetype'] = 'text';
$modversion['config'][23]['default'] = 'D, d-M-Y';

$modversion['config'][44]['name'] = 'totalchars';
$modversion['config'][44]['title'] = '_MI_WFB_TOTALCHARS';
$modversion['config'][44]['description'] = '_MI_WFB_TOTALCHARSDSC';
$modversion['config'][44]['formtype'] = 'select';
$modversion['config'][44]['valuetype'] = 'int';
$modversion['config'][44]['default'] = 200;
$modversion['config'][44]['options'] = array( '100' => 100, '200' => 200, '300' => 300, '400' => 400, '500' => 500, '750' => 750 );

$modversion['config'][31]['name'] = 'keywordlength';
$modversion['config'][31]['title'] = '_MI_WFB_KEYLENGTH';
$modversion['config'][31]['description'] = '_MI_WFB_KEYLENGTHDSC';
$modversion['config'][31]['formtype'] = 'textbox';
$modversion['config'][31]['valuetype'] = 'int';
$modversion['config'][31]['default'] = 255;

$modversion['config'][45]['name'] = 'otherlinks';
$modversion['config'][45]['title'] = '_MI_WFB_OTHERLINKS';
$modversion['config'][45]['description'] = '_MI_WFB_OTHERLINKSDSC';
$modversion['config'][45]['formtype'] = 'yesno';
$modversion['config'][45]['valuetype'] = 'int';
$modversion['config'][45]['default'] = 1;

$modversion['config'][46]['name'] = 'quickview';
$modversion['config'][46]['title'] = '_MI_WFB_QUICKVIEW';
$modversion['config'][46]['description'] = '_MI_WFB_QUICKVIEWDSC';
$modversion['config'][46]['formtype'] = 'yesno';
$modversion['config'][46]['valuetype'] = 'int';
$modversion['config'][46]['default'] = 1;

$modversion['config'][47]['name'] = 'showsbookmarks';
$modversion['config'][47]['title'] = '_MI_WFB_SHOWSBOOKMARKS';
$modversion['config'][47]['description'] = '_MI_WFB_SHOWSBOOKMARKSDSC';
$modversion['config'][47]['formtype'] = 'yesno';
$modversion['config'][47]['valuetype'] = 'int';
$modversion['config'][47]['default'] = 1;

$modversion['config'][48]['name'] = 'showpagerank';
$modversion['config'][48]['title'] = '_MI_WFB_SHOWPAGERANK';
$modversion['config'][48]['description'] = '_MI_WFB_SHOWPAGERANKSDSC';
$modversion['config'][48]['formtype'] = 'yesno';
$modversion['config'][48]['valuetype'] = 'int';
$modversion['config'][48]['default'] = 1;

$modversion['config'][49]['name'] = 'usercantag';
$modversion['config'][49]['title'] = '_MI_WFB_USERTAGDESCR';
$modversion['config'][49]['description'] = '_MI_WFB_USERTAGDSC';
$modversion['config'][49]['formtype'] = 'yesno';
$modversion['config'][49]['valuetype'] = 'int';
$modversion['config'][49]['default'] = 0;

$modversion['config'][24]['name'] = 'showdisclaimer';
$modversion['config'][24]['title'] = '_MI_WFB_SHOWDISCLAIMER';
$modversion['config'][24]['description'] = '_MI_WFB_SHOWDISCLAIMERDSC';
$modversion['config'][24]['formtype'] = 'yesno';
$modversion['config'][24]['valuetype'] = 'int';
$modversion['config'][24]['default'] = 0;

$modversion['config'][25]['name'] = 'disclaimer';
$modversion['config'][25]['title'] = '_MI_WFB_DISCLAIMER';
$modversion['config'][25]['description'] = '_MI_WFB_DISCLAIMERDSC';
$modversion['config'][25]['formtype'] = 'textarea';
$modversion['config'][25]['valuetype'] = 'text';
$modversion['config'][25]['default'] = 'We have the right, but not the obligation to monitor and review submissions submitted by users, in the forums. We shall not be responsible for any of the content of these messages. We further reserve the right, to delete, move or edit submissions that the we, in its exclusive discretion, deems abusive, defamatory, obscene or in violation of any Copyright or Trademark laws or otherwise objectionable.';

$modversion['config'][29]['name'] = 'showlinkdisclaimer';
$modversion['config'][29]['title'] = '_MI_WFB_SHOWLINKDISCL';
$modversion['config'][29]['description'] = '_MI_WFB_SHOWLINKDISCLDSC';
$modversion['config'][29]['formtype'] = 'yesno';
$modversion['config'][29]['valuetype'] = 'int';
$modversion['config'][29]['default'] = 0;

$modversion['config'][30]['name'] = 'linkdisclaimer';
$modversion['config'][30]['title'] = '_MI_WFB_LINKDISCLAIMER';
$modversion['config'][30]['description'] = '_MI_WFB_LINKDISCLAIMERDSC';
$modversion['config'][30]['formtype'] = 'textarea';
$modversion['config'][30]['valuetype'] = 'text';
$modversion['config'][30]['default'] = 'The links on this site are provided as is without warranty either expressed or implied. linkloaded files should be checked for possible virus infection using the most up-to-date detection and security packages. If you have a question concerning a particular piece of software, feel free to contact the developer. We refuse liability for any damage or loss resulting from the use or misuse of any software offered from this site for linkloading. If you have any doubt at all about the safety and operation of software made available to you on this site, do not linkload it.<br /><br />Contact us if you have questions concerning this disclaimer.';

$modversion['config'][40]['name'] = 'copyright';
$modversion['config'][40]['title'] = '_MI_WFB_COPYRIGHT';
$modversion['config'][40]['description'] = '_MI_WFB_COPYRIGHTDSC';
$modversion['config'][40]['formtype'] = 'yesno';
$modversion['config'][40]['valuetype'] = 'int';
$modversion['config'][40]['default'] = 1;

$modversion['config'][43]['name'] = 'selectforum';
$modversion['config'][43]['title'] = '_MI_WFB_SELECTFORUM';
$modversion['config'][43]['description'] = '_MI_WFB_SELECTFORUMDSC';
$modversion['config'][43]['formtype'] = 'select';
$modversion['config'][43]['valuetype'] = 'int';
$modversion['config'][43]['default'] = 1;
$modversion['config'][43]['options'] = array( '_MI_WFB_DISPLAYFORUM1' => 1, '_MI_WFB_DISPLAYFORUM2' => 2, '_MI_WFB_DISPLAYFORUM3' => 3 );

// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'wfbooks_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_WFB_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_WFB_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array( 'index.php', 'viewcat.php', 'singlelink.php' );

$modversion['notification']['category'][2]['name'] = 'category';
$modversion['notification']['category'][2]['title'] = _MI_WFB_CATEGORY_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_WFB_CATEGORY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array( 'viewcat.php', 'singlelink.php' );
$modversion['notification']['category'][2]['item_name'] = 'cid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name'] = 'link';
$modversion['notification']['category'][3]['title'] = _MI_WFB_LINK_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_WFB_FILE_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = 'singlelink.php';
$modversion['notification']['category'][3]['item_name'] = 'lid';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_category';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_WFB_GLOBAL_NEWCATEGORY_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_WFB_GLOBAL_NEWCATEGORY_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_WFB_GLOBAL_NEWCATEGORY_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newcategory_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_WFB_GLOBAL_NEWCATEGORY_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'link_modify';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['admin_only'] = 1;
$modversion['notification']['event'][2]['title'] = _MI_WFB_GLOBAL_LINKMODIFY_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_WFB_GLOBAL_LINKMODIFY_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_WFB_GLOBAL_LINKMODIFY_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_linkmodify_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_WFB_GLOBAL_LINKMODIFY_NOTIFYSBJ;

$modversion['notification']['event'][3]['name'] = 'link_broken';
$modversion['notification']['event'][3]['category'] = 'global';
$modversion['notification']['event'][3]['admin_only'] = 1;
$modversion['notification']['event'][3]['title'] = _MI_WFB_GLOBAL_LINKBROKEN_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_WFB_GLOBAL_LINKBROKEN_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_WFB_GLOBAL_LINKBROKEN_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_linkbroken_notify';
$modversion['notification']['event'][3]['mail_subject'] = _MI_WFB_GLOBAL_LINKBROKEN_NOTIFYSBJ;

$modversion['notification']['event'][4]['name'] = 'link_submit';
$modversion['notification']['event'][4]['category'] = 'global';
$modversion['notification']['event'][4]['admin_only'] = 1;
$modversion['notification']['event'][4]['title'] = _MI_WFB_GLOBAL_LINKSUBMIT_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_WFB_GLOBAL_LINKSUBMIT_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_WFB_GLOBAL_LINKSUBMIT_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'global_linksubmit_notify';
$modversion['notification']['event'][4]['mail_subject'] = _MI_WFB_GLOBAL_LINKSUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][5]['name'] = 'new_link';
$modversion['notification']['event'][5]['category'] = 'global';
$modversion['notification']['event'][5]['title'] = _MI_WFB_GLOBAL_NEWLINK_NOTIFY;
$modversion['notification']['event'][5]['caption'] = _MI_WFB_GLOBAL_NEWLINK_NOTIFYCAP;
$modversion['notification']['event'][5]['description'] = _MI_WFB_GLOBAL_NEWLINK_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = 'global_newfile_notify';
$modversion['notification']['event'][5]['mail_subject'] = _MI_WFB_GLOBAL_NEWLINK_NOTIFYSBJ;

$modversion['notification']['event'][6]['name'] = 'link_submit';
$modversion['notification']['event'][6]['category'] = 'category';
$modversion['notification']['event'][6]['admin_only'] = 1;
$modversion['notification']['event'][6]['title'] = _MI_WFB_CATEGORY_FILESUBMIT_NOTIFY;
$modversion['notification']['event'][6]['caption'] = _MI_WFB_CATEGORY_FILESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][6]['description'] = _MI_WFB_CATEGORY_FILESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = 'category_linksubmit_notify';
$modversion['notification']['event'][6]['mail_subject'] = _MI_WFB_CATEGORY_FILESUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][7]['name'] = 'new_link';
$modversion['notification']['event'][7]['category'] = 'category';
$modversion['notification']['event'][7]['title'] = _MI_WFB_CATEGORY_NEWLINK_NOTIFY;
$modversion['notification']['event'][7]['caption'] = _MI_WFB_CATEGORY_NEWLINK_NOTIFYCAP;
$modversion['notification']['event'][7]['description'] = _MI_WFB_CATEGORY_NEWLINK_NOTIFYDSC;
$modversion['notification']['event'][7]['mail_template'] = 'category_newfile_notify';
$modversion['notification']['event'][7]['mail_subject'] = _MI_WFB_CATEGORY_NEWLINK_NOTIFYSBJ;

$modversion['notification']['event'][8]['name'] = 'approve';
$modversion['notification']['event'][8]['category'] = 'link';
$modversion['notification']['event'][8]['invisible'] = 1;
$modversion['notification']['event'][8]['title'] = _MI_WFB_LINK_APPROVE_NOTIFY;
$modversion['notification']['event'][8]['caption'] = _MI_WFB_LINK_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][8]['description'] = _MI_WFB_LINK_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][8]['mail_template'] = 'link_approve_notify';
$modversion['notification']['event'][8]['mail_subject'] = _MI_WFB_LINK_APPROVE_NOTIFYSBJ;

// On Update
if ( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] )
{
    include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
} 

?>